# Generated by Django 5.1.5 on 2025-01-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
