# Generated by Django 5.1.5 on 2025-01-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='No_Image_Available.jpg', null=True, upload_to='profile_pic/'),
        ),
    ]
